CREATE TABLE movies(
    m_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    m_title VARCHAR(50) NOT NULL,
    m_description VARCHAR(255) NOT NULL,
    m_release DATETIME NOT NULL,
    m_genre VARCHAR(10) NOT NULL,
    m_created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    m_apdated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);